### ISSUE TITLE
Multiple sequensing runs

### ISSUE THREAD

**Issue by mariafiruleva** [pachterlab/kallistobustools#12]
Dear kallisto team,

First of all, thanks for your amazing tool.

I want to clarify, in case I have multiple sequencing runs, is it correct to use `cat` for merging corresponding fastq files?

For example, I want to analyze *SRS_Z* which contains *SRR_X* and *SRR_Y* runs.

```
cat SRR*2.fastq > barcode.fastq # merge SRR_X_2.fastq and SRR_Y_2.fastq
cat SRR*3.fastq > bio.fastq # merge SRR_X_3.fastq and SRR_Y_3.fastq
kallisto bus -i references/Mus_musculus.GRCm38.cdna.all.idx -x 10xv2 -t 4 -o bus_out/ barcode.fastq bio.fastq
# other steps like correct -> sort -> count
```

Best wishes,
Maria

**Comment by gaofan83** [comment]
Should be fine to `cat` if the fastq files come from the same sample library (e.g., collected from multiple sequencing runs).

**Comment by ArnonCyto** [comment]
@gaofan83  if we don't cat the samples, provide 4 files. What is the default behavior?
