### ISSUE TITLE
 kallistobus for MARSseq data

### ISSUE THREAD

**Issue by ogandril** [pachterlab/kallistobustools#13]
Dear authors
In the actual version of kallistobus, the -x Technology argument does not incorporates MARSseq technology.
Any chance this might be implemented soon?
If not, how challenging would that be to implement a -x MARSseq argument?
Best
Olivier

**Comment by gaofan83** [comment]
Hi Olivier,
Please take a look at https://pachterlab.github.io/kallisto/manual. If you know the positions of bc, umi and feature, you should be able to use -x argument.

"Additionally kallisto bus will accept a string specifying a new technology in the format of bc:umi:seq where each of bc,umi and seq are a triplet of integers separated by a comma, denoting the file index, start and stop of the sequence used. For example to specify the 10xV2 technology we would use 0,0,16:0,16,26:1,0,0. The first part bc is 0,0,16 indicating it is in the 0-th file (also known as the first file in plain english), the barcode starts at the 0-th bp and ends at the 16-th bp in the sequence (i.e. 16bp barcode), the UMI is similarly in the same file, right after the barcode in position 16-26 (a 10bp UMI), finally the sequence is in a separate file, starts at 0 and ends at 0 (in this case stopping at 0 means there is no limit, we use the entire sequence)."

**Comment by ogandril** [comment]
Dear Fan

Thank’s a LOT. Very helpful. 

Best

Olivier

**Comment by gaofan83** [comment]
You are welcome.
