### ISSUE TITLE
https://kallistobus.tools/ down?

### ISSUE THREAD

**Issue by PeteHaitch** [pachterlab/kallistobustools#2]
I've tried to access https://kallistobus.tools/ a couple of times this week and each time it's timed out. Is this just me or might the site be down?
Cheers,
Pete

**Comment by lakigigar** [comment]
The link is https://www.kallistobus.tools/ 
Typing kallistobus.tools works as well. 
We'll look into whether we can fix this so https://kallistobus.tools/ also works.

Thanks for reporting this.

**Comment by PeteHaitch** [comment]
Thanks, Lior!
I don't remember why I was trying https://kallistobus.tools/ and not the ones you suggest.
FWIW  http://kallistobus.tools/ **does** work and resolves to https://www.kallistobus.tools/
