### ISSUE TITLE
Cannot install kb using pip

### ISSUE THREAD

**Issue by ekernf01** [pachterlab/kallistobustools#30]
There's an issue with the installation that I think you might be interested in checking out. Running 

```
pip install kb-python
```

gives an error:

```
Collecting kb-python
  Could not find a version that satisfies the requirement kb-python (from versions: )
No matching distribution found for kb-python
```

I'm using `pip 9.0.1`  with `python 2.7` on ubuntu 18.04. I didn't expect this kind of problem because I'm doing this on AWS, so the environment is basically a clean slate (all I did was install pip, pip3, and the aws cli). What am I missing here? Thanks!

**Comment by Lioscro** [comment]
Hi, @ekernf01,
Only Python 3.6 and up are supported! Python 2 has reached end of life in January 1, 2020 and should not be used if at all possible.

**Comment by ekernf01** [comment]
OK. I previously had the same issue using pip3, but it's working now and I'm not able to reproduce the problem. Thanks for your help!
