### ISSUE TITLE
Hardcoded whitelists

### ISSUE THREAD

**Issue by apredeus** [pachterlab/kallistobustools#34]
Hi, 

I was wondering where are the whitelists that are hard-coded into `kb` are located (for the scRNA-seq variants listed with `kb --list`)? I'm particularly interested in the list for INDROPS1/2/3. 

Thank you!

**Comment by Lioscro** [comment]
Hi, @apredeus,
All whitelists we support are provided by the `ngs-tools` Python library and are located here: https://github.com/Lioscro/ngs-tools/tree/main/ngs_tools/chemistry/whitelists
I don't believe we provide whitelists for INDROPS1 or INDROPS2, though, only INDROPS3.

**Comment by apredeus** [comment]
I see, thank you! 

This seems counterintuitive since the barcodes given here are for v2 I think? https://github.com/indrops/indrops/tree/master/ref/barcode_lists

Additionally, barcode list 1 seems to have variable length, but the output of `kb --list` suggests same position for all barcodes. If you could clarify that, it would have been extremely helpful. Thank you in advance!

**Comment by Lioscro** [comment]
My understanding is that the barcodes for v3 is simply every pairwise combination of barcodes in the v2 list, where the second is reverse-complemented. We don't provide whitelists for v1 nor v2 because they have variable lengths.

**Comment by apredeus** [comment]
Thank you!

**Comment by kane9530** [comment]
Hi there, for analyzing the INDROPS V1 data, can I confirm that it's appropriate to point `kb count` to the directory containing the pair of INDROPS barcodes files: [inDrops_barcode_lists](https://github.com/indrops/indrops/tree/master/ref/barcode_lists) via the `-w` flag? Thanks.
