### ISSUE TITLE
How to provide read1 and read2 fastq files from two lanes to `kb count`?

### ISSUE THREAD

**Issue by naity2** [pachterlab/kallistobustools#37]
Dear Authors,

I was wondering how should I provide 10X read1 and read2 fastq files from both lanes to `kb count`?

Thanks very much!

**Comment by Yenaled** [comment]
Just put the lanes one after another, e.g.

R1_lane1.fq R2_lane1.fq R1_lane2.fq R2_lane2.fq

**Comment by naity2** [comment]
> Just put the lanes one after another, e.g.
> 
> R1_lane1.fq R2_lane1.fq R1_lane2.fq R2_lane2.fq

Great, thank you!
