### ISSUE TITLE
Mito genes not having '-' in the t2g.txt

### ISSUE THREAD

**Issue by GabyBG** [pachterlab/kallistobustools#40]
Hello!

Thank you so much for developing this tool, it comes handy specially when trying to prepare to run RNA velocity analysis.

Recently I have generated my index using the following command:
```
kb ref -i index.idx -g t2g.txt -f1 cdna.fa -f2 intron.fa -c1 spliced_t2c.txt -c2 unspliced_t2c.txt --workflow lamanno /path_ref/genome.fa /path_ref/Homo_sapiens.GRCh38.105.gtf
```

Then quantified my sample with this command:
```
kb count --loom -i /path_ref/kb_lamanno_index/index.idx -g /path_ref/kb_lamanno_index/t2g.txt -x 10xv2 -o Sample_01 -c1 /path_ref/kb_lamanno_index/spliced_t2c.txt -c2 /path_ref/unspliced_t2c.txt --workflow lamanno --filter bustools sample1_R1.fastq.gz sample2_R2.fastq.gz
```
When processing my data with Scanpy, at the moment of calculating percent.mt I was not finding any genes that started with 'MT-'. Then I went back to my t2g.txt file, to find that there was actually no MT- genes. I think the '-' was removed at some point. I also checked that my GTF had the MT- genes, and they were there. Maybe I missed it in the documentation, but any help is really appreciated.

Thank you so much for your help!

**Comment by Yenaled** [comment]
Strange. As far as I know, the - shouldn't be removed. Can you share your t2g.txt file with me?

**Comment by GabyBG** [comment]
Thank you for your quick response, I compressed the file and it is attached here
[t2g.txt.gz](https://github.com/pachterlab/kallistobustools/files/8922237/t2g.txt.gz)
l

**Comment by Yenaled** [comment]
Hmm, ok, I looked in the GTF and there are MT genes there (e.g. ENSG00000210195). However, in your t2g file, that gene (and in fact, all of its associated transcripts) are absent.

What genome.fa are you using? I suspect that the MT chromosome is missing (or named something else) in your genome.fa FASTA file.

**Comment by GabyBG** [comment]
For some reason my genome reference has chrM and not chrMT as in the GTF. Thank you so much for pointing that out. I will fix that and re-run, but I think this should solve this issue.

**Comment by liliay** [comment]
Hi there, 

rist of all thank you for sharing you experiences regarding kb, very appreciated. 
I am not facing the exact same problem but regarding the comments, some of you could help. 
I am buiding a mouse index using kb ref with the following command line : 

`kb ref -i index_mm_98.idx -g t2g.txt -f1 /home/younsi/cdna.fa  -f2 ./introns.fa -c1 cDNA_t2c.txt -c2 introns_t2c.txt --workflow=lamanno ./Mus_musculus.GRCm38.cdna.all.fa ./Mus_musculus.GRCm38.98.gtf --overwrite` 

According to the t2g file @GabyBG posted, this command is supposed to return something similar. 
In my case, after running the kb ref, t2g.txt is... EMPTY. 

Does anyone know what I could be doing wrong ? 


Thanks in advance for your help :)
