### ISSUE TITLE
kb ref returns empty 'to be generated' files

### ISSUE THREAD

**Issue by liliay** [pachterlab/kallistobustools#44]
Hi there,

First of all thank you to the developpers, kb is very helpful with my velocity project. 

I am buiding a mouse index using kb ref with the following command line :

`kb ref -i index_mm_98.idx -g t2g.txt -f1 /home/younsi/cdna.fa -f2 ./introns.fa -c1 cDNA_t2c.txt -c2 introns_t2c.txt --workflow=lamanno ./Mus_musculus.GRCm38.cdna.all.fa ./Mus_musculus.GRCm38.98.gtf --overwrite`

In my case, after running the kb ref, t2g.txt, cDNA_t2c.txt and introns_t2c.txt files are... EMPTY.
As I look back at the kb --help, I understand that all of these parameters are supposed to be generated : 

```
required arguments:
  -i INDEX              Path to the kallisto index **to be constructed.**
  -g T2G                Path to transcript-to-gene mapping **to be generated**
  -f1 FASTA             [Optional with -d] Path to the cDNA FASTA (lamanno, nucleus) or mismatch FASTA (kite) **to be generated**

required arguments for `lamanno` and `nucleus` workflows:
  -f2 FASTA             Path to the intron FASTA **to be generated**
  -c1 T2C               Path **to generate** cDNA transcripts-to-capture
  -c2 T2C               Path **to generate** intron transcripts-to-capture
```

There is something very unclear to me, what could I be doing wrong ?

Thank you in advance ! :)

**Comment by Yenaled** [comment]
The problem is you are supposed to supply a GENOME fasta file, not a cdna fasta file (aka Mus_musculus.GRCm38.cdna.all.fa is incorrect).

**Comment by liliay** [comment]
Thank you for your help. Unfortunately I re-downloaded mus musculus genome.fa and genes.gtf (the ones from 10X for cellranger) and it still does not work for me : all generated files are still empty after running kb ref

**Comment by Yenaled** [comment]
Please tell me which files you're downloading (i.e. provide a link to the actual file and/or show the first 10 lines of the genome+gtf files).

If you look at the 10X website https://support.10xgenomics.com/single-cell-gene-expression/software/release-notes/build and click "Mouse reference, mm10 (GENCODE vM23/Ensembl 98)", they show that they get their genome FASTA from http://ftp.ensembl.org/pub/release-98/fasta/mus_musculus/dna/Mus_musculus.GRCm38.dna.primary_assembly.fa.gz and their GTF from http://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M23/gencode.vM23.primary_assembly.annotation.gtf.gz

You can try using those files.

Finally, make sure you're building your index on a server that has 70 gb of RAM, otherwise you won't be able to build the index (building a cDNA+intron index takes a lot of memory -- which will hopefully be improved in the near future).

**Comment by liliay** [comment]
Here is the link to the mouse reference genome provided by cellranger, you can get it using this command : 
curl -O https://cf.10xgenomics.com/supp/cell-exp/refdata-gex-mm10-2020-A.tar.gz 
(link to the cellranger page https://support.10xgenomics.com/single-cell-gene-expression/software/downloads/latest)

What surprises me is that the command runs properly for like 2 to 3 hours on the server), no errors, and displays that kb ref command was successful), but when i look at the final files content there is nothing.

**Comment by Yenaled** [comment]
I just ran it on my end -- it seems to work perfectly fine.

`kb ref -i index_mm_98.idx -g t2g.txt -f1 ./cdna.fa -f2 ./introns.fa -c1 cDNA_t2c.txt -c2 introns_t2c.txt --workflow=lamanno genome.fa genes.gtf --overwrite
`

Can you post the full output of your kb ref command?

**Comment by liliay** [comment]
Can you please share with me your txt files (at least t2g.txt) so that i should've gotten ? 
I will be rerunning the command and letting you know the output of it asap. Thank you again !

**Comment by liliay** [comment]
> I just ran it on my end -- it seems to work perfectly fine.
> 
> `kb ref -i index_mm_98.idx -g t2g.txt -f1 ./cdna.fa -f2 ./introns.fa -c1 cDNA_t2c.txt -c2 introns_t2c.txt --workflow=lamanno genome.fa genes.gtf --overwrite `
> 
> Can you post the full output of your kb ref command?

Here is the command output : 
![image](https://user-images.githubusercontent.com/45742503/193566087-f40ef4ca-a62e-4a07-a1c0-494db20febc0.png)


Plus, I checked and the server I am running the command on is 256G RAM.

**Comment by Yenaled** [comment]
Hi sorry, for the delay in responding, but I can't figure out what's wrong. Here's my output:

```
kb ref -i index_mm_98.idx -g t2g.txt -f1 ./cdna.fa -f2 ./introns.fa -c1 cDNA_t2c.txt -c2 introns_t2c.txt --workflow=lamanno genome.fa genes.gtf --overwrite
[2022-10-10 06:18:31,240]    INFO [ref_lamanno] Preparing genome.fa, genes.gtf 
[2022-10-10 06:20:10,606]    INFO [ref_lamanno] Splitting genome genome.fa into
cDNA at /home/dsullivan/tt/kallisto-bf/build/tmp/tmpth_wzl8e           
[2022-10-10 06:21:56,065]    INFO [ref_lamanno] Creating cDNA transcripts-to-capture at /home/dsullivan/tt/kallisto-bf/build/tmp/tmpm7qqlhxr           
[2022-10-10 06:21:57,076]    INFO [ref_lamanno] Splitting genome into introns at /home/dsullivan/tt/kallisto-bf/build/tmp/tmp96apnhas                  
[2022-10-10 06:29:31,245]    INFO [ref_lamanno] Creating intron transcripts-to-capture at /home/dsullivan/tt/kallisto-bf/build/tmp/tmposdka4kc         
[2022-10-10 06:29:40,700]    INFO [ref_lamanno] Concatenating 1 cDNA FASTAs to ./cdna.fa
[2022-10-10 06:29:43,737]    INFO [ref_lamanno] Concatenating 1 cDNA transcripts-to-captures to cDNA_t2c.txt
[2022-10-10 06:29:43,830]    INFO [ref_lamanno] Concatenating 1 intron FASTAs to ./introns.fa
[2022-10-10 06:30:27,400]    INFO [ref_lamanno] Concatenating 1 intron transcripts-to-captures to introns_t2c.txt
[2022-10-10 06:30:27,985]    INFO [ref_lamanno] Concatenating cDNA and intron FASTAs to /home/dsullivan/tt/kallisto-bf/build/tmp/tmplb90spy3           
[2022-10-10 06:31:12,289]    INFO [ref_lamanno] Creating transcript-to-gene mapping at t2g.txt
[2022-10-10 06:31:35,537]    INFO [ref_lamanno] Indexing /home/dsullivan/tt/kallisto-bf/build/tmp/tmplb90spy3 to index_mm_98.idx                       
```

The first few lines of t2g.txt should look like:

```
ENSMUST00000159265.1    ENSMUSG00000051951.5    Xkr4    Xkr4-202        chr1   3206523  3215632 -
ENSMUST00000070533.4    ENSMUSG00000051951.5    Xkr4    Xkr4-201        chr1   3214482  3671498 -
ENSMUST00000162897.1    ENSMUSG00000051951.5    Xkr4    Xkr4-203        chr1   3205901  3216344 -
ENSMUST00000161581.1    ENSMUSG00000089699.1    Gm1992  Gm1992-201      chr1   3466587  3513553 +
ENSMUST00000192692.1    ENSMUSG00000102331.1    Gm19938 Gm19938-201     chr1   3647309  3658904 -
ENSMUST00000194643.1    ENSMUSG00000102343.1    Gm37381 Gm37381-202     chr1   3905739  3986215 -
ENSMUST00000192427.1    ENSMUSG00000102343.1    Gm37381 Gm37381-201     chr1   3984225  3985984 -
ENSMUST00000208660.1    ENSMUSG00000025900.12   Rp1     Rp1-203 chr1    39995574409241  -
ENSMUST00000208793.1    ENSMUSG00000025900.12   Rp1     Rp1-204 chr1    42908464409241  -
ENSMUST00000027032.5    ENSMUSG00000025900.12   Rp1     Rp1-201 chr1    43441464360314  -

```

I imagine that it's a server-specific issue since everything seems to work fine on my end. Maybe try a non-velocity workflow (aka build an index without introns) and see if that works? It'll be easier to debug what's wrong on a workflow that requires very little time / memory.

**Comment by liliay** [comment]
Hi there, I ma closing the issue cause it ended up working without the need to change anything... Can't explain why but works perfectly ! 
Thank you for your precious help and time ! :)
