### ISSUE TITLE
kb count subprocess.CalledProcessError: 

### ISSUE THREAD

**Issue by victorcat4** [pachterlab/kallistobustools#49]
Hello, 

I get the error bellow when I run the following cmd :
kb count -i index.idx -g t2g.txt --overwrite -t 1 -m 120G -x 10xv3 singlecell.fastq.gz

Error : 

raise sp.CalledProcessError(p.returncode, ' '.join(command))
subprocess.CalledProcessError: Command '/n/home03/user1/R/ifxrstudio/RELEASE_3_15/python-user-base/lib/python3.8/site-packages/kb_python/bins/linux/kallisto/kallisto bus -i index.idx -x 10xv3 -t 1 test.fastq.gz' returned non-zero exit status 1.

Does anyone has an idea how to solve this ? I tried different stuff but non of them worked. It doesn't work neither with the fastq.gz nor the fastq. I'm wondering if my index file is too big (3.2Gb)

**Comment by Yenaled** [comment]
Run the command with --verbose so we can see more output and help you debug.

Also, 10Xv3 should have two fastq files (you only supplied one).

**Comment by victorcat4** [comment]
Thanks ! I run -- verbose, it was indeed the problem !
