### ISSUE TITLE
kallisto rna velocity RCPP issue

### ISSUE THREAD

**Issue by yaolutian** [pachterlab/kallistobustools#7]
Hi

I am trying to use kallisto way for the RNA velocity, when at the RCPP step, I ran into problems.

I created the .cpp file using 

//[[Rcpp::depends(RcppProgress)]]
#include <progress.hpp>
#include <progress_bar.hpp>
#include <Rcpp.h>
using namespace Rcpp;

//[[Rcpp::export]]
NumericMatrix bc_ranks2(NumericVector x, NumericVector y, 
                        NumericVector x_grid, NumericVector y_grid) {
  NumericMatrix out(x_grid.size(), y_grid.size());
  Progress p(x_grid.size(), true);
  for (int i = 0; i < x_grid.size(); i++) {
    checkUserInterrupt();
    for (int j = 0; j < y_grid.size(); j++) {
      out(i,j) = sum((x_grid[i] <= x) & (y_grid[j] <= y));
    }
    p.increment();
  }
  return(out);
}

when running it, the error shown:

make: *** No rule to make target `rcpp.o', needed by `sourceCpp_7.so'.  Stop.

Error in Rcpp::sourceCpp("Large_files/velocity rcpp.cpp") : 
  Error 1 occurred building shared library.

can you help me with this?

Thanks

**Comment by lambdamoses** [comment]
I can't reproduce this and it did successfully compile on both Linux (gcc 4.8.5) and Mac (clang8 from CRAN) and the C++ function did work. Which compiler are you using? Also, what's your operating system?

**Comment by yaolutian** [comment]
> I can't reproduce this and it did successfully compile on both Linux (gcc 4.8.5) and Mac (clang8 from CRAN) and the C++ function did work. Which compiler are you using? Also, what's your operating system?

Thanks a lot for your reply! I use R 3.6 in Mac, while somehow I succeeded in making the loom file using velocyto.py. I will give this a try in the future.

**Comment by lambdamoses** [comment]
You don't need to get that C++ function to work to proceed to downstream RNA velocity analysis. That function was written merely to generalize the knee plot to two variables, but was not used in any other way.
